#install.packages("DT")
#library(shiny)
library(DT)

# Define server logic ----
server <- function(input, output) {
  
}

# Run the app ----

#to do list
#1.formulate UI in columns rows
#3.Populate the UI with visualizations
#4.

ui <- navbarPage("Waste Management in Armenia",
                 tabPanel("Overview"),
                 navbarMenu("Data tables",
                            tabPanel("Quantity indicators and transportation"),
                            tabPanel("Waste generated in tons 2017"),
                            tabPanel("waste generated by class 2017")),
                 
                 sidebarLayout(
                   sidebarPanel(width = 3,
                     selectInput("region", "Select Region", 
                                 choices = list("All Regions" = 1,
                                                "Aragatsotn" = 2,
                                                "Ararat" = 3,
                                                "Armavir" = 4,
                                                "Gegharkunik" = 5,
                                                "Lori" = 6,
                                                "Kotayk" = 7,
                                                "Shirak" = 8,
                                                "Syunik" = 9,
                                                "Vayots Dzor" = 10,
                                                "Yerevan city" = 11, selected = 1))
                   ),
                   mainPanel(
                     fluidPage(
                       fluidRow(
                         column(3, h4("Regional Map")),
                         column(5, h4("Bar Chart"))
                       ),
                       fluidRow(
                         column(3, h4("Important numbers")),
                         column(5, h4("Time-Bound info"))
                       )
                     )
                   )
                 )
                 
                 
)

shinyApp(ui = ui, server = server)
