#install.packages("DT")
#install.packages("shinythemes")
#install.packages("intrval")
library(shiny)
library(DT)
library(shinythemes)
library(intrval)
library("plyr")
library("rgeos")
library("maptools")
#install.packages("shinydashboard")
library("shinydashboard")
# Define server logic ----
server <- function(input, output) {
  
}

# Run the app ----

#to do list
#1.formulate UI in columns rows
#3.Populate the UI with visualizations
#4.
# 
# ui <- navbarPage(theme = shinytheme("cerulean"), "Waste Management in Armenia",
#                  tabPanel("Overview"),
#                  navbarMenu("Data tables",
#                             tabPanel("Quantity indicators and transportation"),
#                             tabPanel("Waste generated in tons 2017"),
#                             tabPanel("waste generated by class 2017")),
#                  
#                  sliderInput("year_slider", h4("Choose year range"), min = 2013, max = 2017, value = c(2013,2017), step = NULL, round = FALSE
#                             ),
#                  textInput("Years to exclude", "Type year to exclude"),
#                  
#                  
#                    sidebarPanel(width = 3,
#                                  checkboxGroupInput("region", "Select Region", 
#                                  choices = list("All Regions" = 1,
#                                                 "Aragatsotn" = 2,
#                                                 "Ararat" = 3,
#                                                 "Armavir" = 4,
#                                                 "Gegharkunik" = 5,
#                                                 "Lori" = 6,
#                                                 "Kotayk" = 7,
#                                                 "Shirak" = 8,
#                                                 "Syunik" = 9,
#                                                 "Vayots Dzor" = 10,
#                                                 "Yerevan city" = 11))
#                    ),
#                    mainPanel(
#                      fluidPage(
#                        fluidRow(
#                          column(3, h4("Regional Map")),
#                          column(5, h4("Bar Chart"))
#                        ),
#                        fluidRow(
#                          column(3, infoBox("Testing stuff", 20, icon = icon("credit-card"), fill = TRUE)),
#                          column(5, h4("Time-Bound info"))
#                        ),
#                        fluidRow(
#                          box(width = 4, actionButton("count", "Increment progress"))
#                        )
#                      )
#                    )
#                  )
#                  
                 
  ui <- dashboardPage(
    dashboardHeader(title = "Waste management in Armenia"),
    dashboardSidebar(
      sidebarMenu(
        id = "tabs",
        menuItem("Overview", tabName = "overview", icon = icon("dashboard")),
        menuItem("Tables", tabName = "tables", icon = icon("table")),
        sliderInput("year_slider", h4("Choose year range"), min = 2013, max = 2017, value = c(2013,2017), step = NULL, round = FALSE),
        textInput("Years to exclude", "Type year to exclude"),
        checkboxGroupInput("region", "Select Region", 
                           choices = list("All Regions" = 1,
                                          "Aragatsotn" = 2,
                                          "Ararat" = 3,
                                          "Armavir" = 4,
                                          "Gegharkunik" = 5,
                                          "Lori" = 6,
                                          "Kotayk" = 7,
                                          "Shirak" = 8,
                                          "Syunik" = 9,
                                          "Vayots Dzor" = 10,
                                          "Yerevan city" = 11))
      )
    ),
    dashboardBody(
      tabItems(
        tabItem(tabName = "overview",
                fluidPage(
                  fluidRow(
                    column(3, h4("Test")),
                    column(5, h4("Bar Chart"))
                  ),
                  fluidRow(
                    column(3, infoBox("Testing stuff", 20, icon = icon("credit-card"), fill = TRUE)),
                    column(5, h4("Time-Bound info"))
                  )
                )     
                ),
        tabItem(tabName = "tables", 
                fluidPage(
                  fluidRow(
                    tabBox(
                      title = "Environmental Data",
                      # The id lets us use input$tabset1 on the server to find the current tab
                      id = "tabset1", width = 775,
                      tabPanel("Tab1", datatable(waste_transported2017)),
                      tabPanel("Tab2", "Tab content 2")
                    )
                  )
                ) 
                )
      )
      
    )
  )
  
  shinyApp(ui = ui, server = server)
